# Generated by Django 4.2.1 on 2023-05-27 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_comment_user_comment_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
    ]
