# Generated by Django 4.2.1 on 2023-05-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='media/defaultavatar.png', null=True, upload_to='profiles'),
        ),
    ]
